spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: email-database
      username: root
      password: example
      authentication-database: admin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  mail:
    host: smtp.gmail.com
    port: 587
    username: tlrferreira83@gmail.com
    password: cliw hvuu mwve phuy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081

mq:
  queues:
    email-queue: default-email-queue
